### ISSUE TITLE
Deploy to Heroku

### ISSUE THREAD

**Issue by gaelyn** [gaelyn/viewing_party#18]
In addition to the normal deployment, you will also need to set up any API keys manually for your Heroku production environment.

[Heroku Docs](https://devcenter.heroku.com/articles/git#creating-a-heroku-remote)

[Heroku Old Notes](https://gist.github.com/Diana20920/7485f63eaf18d34291216ca084f8efe0) (stack may not need to be set)

**Comment by Diana20920** [comment]
We were able to confirm that it works after:
- completing `welcome page`
- deploying
- running `heroku open` on local terminal

And seeing that our Welcome page displays what we intended.
