### ISSUE TITLE
Consume additional API endpoints

### ISSUE THREAD

**Issue by gaelyn** [gaelyn/viewing_party#5]
Explore additional endpoints that could be consumed from [The MovieDB API](https://developers.themoviedb.org/3/getting-started/introduction). Choose **2** additional endpoints to consume and display within the application.

**Comment by Diana20920** [comment]
[Endpoint 1: Trending](https://developers.themoviedb.org/3/trending/get-trending) 
[Endpoint 2: Movie Recommendations](https://developers.themoviedb.org/3/movies/get-movie-recommendations)
[Endpoint 3: Get Latest Movies](https://developers.themoviedb.org/3/movies/get-latest-movie)
[Endpoint 4: Upcoming](https://developers.themoviedb.org/3/movies/get-upcoming)
